name: Deploy Azure Function App

on:
    push:
        branches:
            - main

env:
    AZURE_FUNCTIONAPP_PACKAGE_PATH: '.' # set this to the path to your web app project, defaults to the repository root
    PYTHON_VERSION: '3.8' # set this to the python version to use (supports 3.6, 3.7, 3.8)
  

jobs:
    build-and-deploy:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout repository
              uses: actions/checkout@v2

            - name: Set up Python
              uses: actions/setup-python@v2
              with:
                python-version: '3.8'
            
            - name: Create and start virtual environment
              run: |
                python -m venv venv
                source venv/bin/activate

            - name: Install dependencies
              run: |
                python -m pip install --upgrade pip
                pip install -r requirements.txt
            
            - name: Set up Environment Variables
              run: |
                  echo "AzureWebJobsStorage=${{ secrets.AzureWebJobsStorage }}" >> $GITHUB_ENV
                  echo "${{ secrets.AZURE_VM_SSH_Key }}" > ssh_key.pem
                  chmod 600 ssh_key.pem
            
            - name: Archive project files
              run: |
                zip -r functionapp.zip .

            - name: Deploy to Azure Function App
              uses: azure/webapps-deploy@v2
              with:
                app-name: 'suafunctions'
                package: functionapp.zip
                publish-profile: ${{ secrets.AZUREAPPSERVICE_PUBLISHPROFILE_34029191F0504C78A89A4D3182E65D38 }}
              